PL/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class ProductoController : Controller
    {

        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result result = new ML.Result(); //instanceamos la clase result 
            ML.Producto producto = new ML.Producto();
            producto.Departamento = new ML.Departamento();

            ML.Result resultDepartamento = BL.Departamento.GetAll();
            result = BL.Producto.GetAll(producto); //llamamos el metodo

            if (result.Correct) //validacion 
            {
                // ML.Producto producto = new ML.Producto();
                producto.Departamento.Departamentos = resultDepartamento.Objects;
                producto.Productos = result.Objects;
                return View(producto);
            }
            else
            {
                ViewBag.Massage = "Ocurrio un error al consultar los productos. ";
                return View();
            }
        }

        [HttpPost]
        public ActionResult GetAll(ML.Producto producto)
        {

            ML.Result result = new ML.Result(); //instanceamos la clase result 
                                                // producto.Departamento = new ML.Departamento();

            ML.Result resultDepartamento = BL.Departamento.GetAll();
            result = BL.Producto.GetAll(producto); //llamamos el metodo

            if (result.Correct) //validacion 
            {
                producto.Productos = result.Objects;
                producto.Departamento.Departamentos = resultDepartamento.Objects;
                return View(producto);
            }
            else
            {
                ViewBag.Massage = "Ocurrio un error al consultar los usuarios. ";
                return View();
            }
        }

        [HttpGet]//muestra las vistas
        public ActionResult Form(int? IdProducto)
        {
            ML.Producto producto = new ML.Producto();
            producto.Proveedor = new ML.Proveedor();
            producto.Departamento = new ML.Departamento();
            producto.Departamento.Area = new ML.Area();


            ML.Result resultDepartamento = BL.Departamento.GetAll();
            // ML.Result resultPaises = BL.Pais.GetAll();

            if (IdProducto == null)
            {
                //usuario.Rol.Roles = resultRol.Objects;
                //usuario.Direccion.Colonia.Municipio.Estado.Pais.Paises = resultPaises.Objects;
                return View(producto);
            }
            else
            {
                //GetbyId
                ML.Result result = BL.Producto.GetById(IdProducto.Value);

                if (result.Correct)
                {
                    producto = (ML.Producto)result.Object;
                    producto.Departamento.Departamentos = resultDepartamento.Objects;
                    //.Direccion.Colonia.Municipio.Estado.Pais.Paises = resultPaises.Objects;

                    //ML.Result resultEstados = BL.Estado.GetByIdPais(usuario.Direccion.Colonia.Municipio.Estado.IdEstado);
                    //usuario.Direccion.Colonia.Municipio.Estado.Estados = resultEstados.Objects;
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al consultar el Usuario";
                }
                return View(producto);
            }
          
        }

        [HttpPost]
        public ActionResult Form(ML.Producto producto)
        {
            IFormFile imagen = Request.Form.Files["IFImage"];

            if (imagen != null)
            {
                //llamar al metodo que convierte a bytes la imagen
                byte[] ImagenBytes = ConvertToBytes(imagen);
                //convierto a base 64 la imagen y la guardo en la propiedad de imagen en el objeto alumno
                producto.Imagen = Convert.ToBase64String(ImagenBytes);
            }

            else
            { 
                ML.Result result = new ML.Result();

                if (producto.IdProducto == 0)
                {
                    //ADD
                    result = BL.Producto.Add(producto);
                    if (result.Correct)
                    {
                        ViewBag.Message = result.Message;
                    }
                    else
                    {
                        ViewBag.Message = "Error" + result.Message;
                    }
                }
                else
                {
                    //Update
                    result = BL.Producto.Update(producto);

                    if (result.Correct)
                    {
                        ViewBag.Massage = "Se actualizo correctamente el producto. " + result.Message;
                        //return PartialView("Modal");
                    }
                    else
                    {
                        ViewBag.Massage = "Error: " + result.Message;
                        //return PartialView("Modal");
                    }
                }
                
            }
            return View("Modal");
        }

        public static byte[] ConvertToBytes(IFormFile imagen)
        {

            using var fileStream = imagen.OpenReadStream();

            byte[] bytes = new byte[fileStream.Length];
            fileStream.Read(bytes, 0, (int)fileStream.Length);

            return bytes;
        }

    }
}

PL/Controllers/VentaProductoController.cs
using Microsoft.AspNetCore.Mvc;

using System.IdentityModel.Tokens.Jwt;

namespace PL.Controllers
{
    public class VentaProductoController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result result = new ML.Result(); //instanceamos la clase result 
            ML.Producto producto = new ML.Producto();
            producto.Departamento = new ML.Departamento();

            ML.Result resultDepartamento = BL.Departamento.GetAll();
            result = BL.Producto.GetAll(producto); //llamamos el metodo

            if (result.Correct) //validacion 
            {
                // ML.Producto producto = new ML.Producto();
                producto.Departamento.Departamentos = resultDepartamento.Objects;
                producto.Productos = result.Objects;
                return View(producto);
            }
            else
            {
                ViewBag.Massage = "Ocurrio un error al consultar los productos. ";
                return View();
            }
        }

        [HttpPost]
        public ActionResult GetAll(ML.Producto producto)
        {

            ML.Result result = new ML.Result(); //instanceamos la clase result 
                                                // producto.Departamento = new ML.Departamento();

            ML.Result resultDepartamento = BL.Departamento.GetAll();
            result = BL.Producto.GetAll(producto); //llamamos el metodo

            if (result.Correct) //validacion 
            {
                // ML.Usuario usuario = new ML.Usuario();
                producto.Productos = result.Objects;
                producto.Departamento.Departamentos = resultDepartamento.Objects;
                return View(producto);
            }
            else
            {
                ViewBag.Massage = "Ocurrio un error al consultar los usuarios. ";
                return View();
            }
        }
        [HttpGet]
        public ActionResult CartPost(ML.Producto producto)
        {
            ML.VentaProducto ventaProducto = new ML.VentaProducto();
            ventaProducto.VentaProductos = new List<object>();

            if (HttpContext.Session.GetString("Producto") == null)
            {
                producto.Stock = producto.Stock = 1;
                ventaProducto.VentaProductos.Add(producto);
                HttpContext.Session.SetString("Producto", Newtonsoft.Json.JsonConvert.SerializeObject(ventaProducto.VentaProductos));
                var session = HttpContext.Session.GetString("Producto");
            }
            else
            {
                var ventaSession = Newtonsoft.Json.JsonConvert.DeserializeObject<List<object>>(HttpContext.Session.GetString("Producto"));

                foreach (var obj in ventaSession)
                {
                    ML.Producto objProducto = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Producto>(obj.ToString());
                    ventaProducto.VentaProductos.Add(objProducto);
                }

                foreach (ML.Producto venta in ventaProducto.VentaProductos.ToList())
                {
                    if (producto.IdProducto == venta.IdProducto)
                    {
                        venta.Stock = venta.Stock + 1;   //True                
                    }
                    else
                    {
                        producto.Stock = producto.Stock = 1; //False
                        ventaProducto.VentaProductos.Add(producto);
                    }
                }
                HttpContext.Session.SetString("Producto", Newtonsoft.Json.JsonConvert.SerializeObject(ventaProducto.VentaProductos));
            }
            if (HttpContext.Session.GetString("Producto") != null)
            {
                ViewBag.Message = "Se ha agregado el producto a tu carrito!";
                return PartialView("Modal");
            }
            else
            {
                ViewBag.Message = "No se pudo agregar tu producto ):";
                return PartialView("Modal");
            }

        }
            [HttpGet]
        public ActionResult ResumenCompra(ML.VentaProducto ventaProducto)
        {
            if (HttpContext.Session.GetString("Producto") == null)
            {
                return View();
            }
            else
            {
                var ventaSession = Newtonsoft.Json.JsonConvert.DeserializeObject<List<object>>(HttpContext.Session.GetString("Producto"));
                ventaProducto.VentaProductos = new List<object>();
                foreach (var obj in ventaSession)
                {
                    ML.Producto objProducto = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Producto>(obj.ToString());
                    ventaProducto.VentaProductos.Add(objProducto);
                }

            }

            return View(ventaProducto);
        }

    }
}

PL/Views/Producto/Form.cshtml
@model ML.Producto
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
  
    <h2>Form</h2>
    <div class="row">

        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Producto", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {

                <div class="form-horizontal">
    
                    @*<div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.IdProducto, new { @class = "hidden" })

                            @Html.TextBoxFor(model => model.IdProducto, new { @class = "hidden form-control" })

                            @Html.ValidationMessageFor(model => model.IdProducto)

                        </div>

                    </div>
*@

                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Nombre)
                              <span class="input-group-text"><i class="bi bi-bag"></i></span>

                            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })

                            @Html.ValidationMessageFor(model => model.Nombre)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.PrecioUnitario)
                             <span class="input-group-text"><i class="bi bi-cash-coin"></i></span>

                            @Html.TextBoxFor(model => model.PrecioUnitario, new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.PrecioUnitario)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Stock)
                              <span class="input-group-text"><i class="bi bi-box-seam-fill"></i></span>

                            @Html.TextBoxFor(model => model.Stock, new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.Stock)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Proveedor.IdProveedor)

                              <span class="input-group-text"><i class="bi bi-person-square"></i></span>

                            @Html.TextBoxFor(model => model.Proveedor.IdProveedor, new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.Proveedor.IdProveedor)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Departamento.IdDepartamento)

                              <span class="input-group-text"><i class="bi bi-pin-map"></i></span>

                            @Html.TextBoxFor(model => model.Departamento.IdDepartamento, new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.Departamento.IdDepartamento)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Descripcion)
                           <span class="input-group-text"><i class="bi bi-file-text"></i></span>

                            @Html.TextBoxFor(model => model.Descripcion, new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.Descripcion)

                        </div>

                    </div>
                    <div class="form-group">
                       
                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Area.IdArea)

                              <span class="input-group-text"><i class="bi bi-pin-map"></i></span>

                            @Html.TextBoxFor(model => model.Area.IdArea, new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.Area.IdArea)

                        </div>

                    </div>
 
                    <div class=" offset-md-12">

                            @Html.LabelFor(model=> model.Imagen)

                            <div class="input-group mb-3">
                                <span class="input-group-text" id="basic-addon1"><i class="bi bi-card-image"></i></span>
                                <input id="IFImage" type='file' class="form-control" name="IFImage" onchange="validateFile(this), readURL(this);  " />
                            </div>

                            @if (Model.Imagen != null)
                            {

                                <img id="Img" src="data:image/*;base64,@Model.Imagen" style="width:250px ; height:250px" />

                            }
                            else
                            {
                                <img id="Img" src="~/Imagen/SinProducto.jpg" style="width:250px ; height:250px" />
                            }
                        </div>
                        @Html.HiddenFor(model => model.Imagen)


                    <div class="form-group">

                       @* <div class="col-md-3">

                            @Html.LabelFor(model => model.Proveedor.IdProveedor)


                            @Html.DropDownListFor(model => model.Proveedor.IdProveedor, new SelectList(Model.Proveedor.Proveedores, "IdProveedor", "Nombre"), "Selecciona un Proveedor", new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.Proveedor.IdProveedor)

                        </div>

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Departamento.IdDepartamento)

                            @Html.DropDownListFor(model => model.Departamento.IdDepartamento, new SelectList(Model.Departamento.Departamentos, "IdDepartamento", "Nombre"), "Selecciona una opcion", new { id = "ddlDepartamento", @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.Departamento.IdDepartamento)

                        </div>      *@      

                    </div>


                    <div class="form-group">

                        <div class="col-md-3">

                            <input type="submit" value="Guardar" class="btn btn-success" />

                            @Html.ActionLink("Regresar", "GetAll", "Producto", htmlAttributes: new { @class = "btn btn-danger" })

                        </div>

                    </div>

                </div>

            }

        </div>

    </div>
</div>

@section Scripts
{
<script src="~/lib/jquery/dist/jquery.js"></script>
<script type="text/javascript">

            $(document).ready(function () {
                $("#ddlDepartamento").change(function () {
                    $("#ddlArea").empty();
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("GetArea")',
                        dataType: 'json',
                        data: { IdDepartamento: $("#ddlDepartamento").val() },
                        success: function (areas) {
                            $("#ddlEstado").append('<option value="0">' + 'Seleccione una opción' + '</option>');
                            $.each(areas, function (i, areas) {
                                $("#ddlEstado").append('<option value="'
                                    + areas.idArea + '">'
                                    + areas.nombre + '</option>');
                            });
                        },
                        error: function (ex) {
                            alert('Failed.' + ex);
                        }
                    });
                })
            })

             $(document).ready(function () {
                $("#ddlDepartamento").change(function () {
                    $("#ddlArea").empty();
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("GetArea")',
                        dataType: 'json',
                        data: { IdDepartamento: $("#ddlDepartamento").val() },
                        success: function (areas) {
                            $("#ddlEstado").append('<option value="0">' + 'Seleccione una opción' + '</option>');
                            $.each(areas, function (i, areas) {
                                $("#ddlEstado").append('<option value="'
                                    + areas.idArea + '">'
                                    + areas.nombre + '</option>');
                            });
                        },
                        error: function (ex) {
                            alert('Failed.' + ex);
                        }
                    });
                })
            })

                  function validateFile()
                {
                    var allowedExtension = ['jpeg', 'jpg'];
                    var fileExtension = document.getElementById('IFImage').value.split('.').pop().toLowerCase();
                    var isValidFile = false;
                        for(var index in allowedExtension) {
                            if(fileExtension === allowedExtension[index]) {
                                isValidFile = true;
                                break;
                            }
                        }
                        if(!isValidFile) {
                            alert('Las extensiones permitidas son : *.' + allowedExtension.join(', *.'));
                            document.getElementById('IFImage').value = ""
                        }
                        return isValidFile;
                }
</script>
}

PL/Views/Producto/GetAll.cshtml
@model ML.Producto
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2> Productos </h2>
    <h3 class="text-center"> Administrador de Productos </h3>
    </div>

    @* Encabezado *@
     <div class="container">
           <h3 class="text-black"> Filtrar por:  </h3>
          
           <div class="row">
 
              @using (Html.BeginForm("GetAll", "Producto", FormMethod.Post,new { enctype = "multipart/form-data" }))
             {
                 <div class="col-md-3">
                   @Html.DropDownListFor(model => model.Departamento.IdDepartamento, new SelectList(Model.Departamento.Departamentos, "IdDepartamento", "Nombre"), "Selecciona una opción", new { @class = "form-control" })
                 </div>
                 <div class="col-md-3">
                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @placeholder = "Nombre" })
                </div>

                <div class="col-md-3">
                <input type="submit" value="Buscar" class="btn btn-success" />
                </div>
             }
        
          </div>
     
         @Html.ActionLink("Agregar +", "Form", "Producto", htmlAttributes: new { @class = "btn btn-success" })
      
     </div>
     

     @* Tabla de productos *@
    <div class="container center-block">

        <div class="row">
            <table class="table table-hover table-responsive" id="tblProducto">
                <thead>
                   <tr>
                    <th>Editar</th>
               @*<th class="hidden">IdProducto</th>*@
                    <th>Nombre</th>
                    <th>PrecioUnitario</th>
                    <th>Stock</th>
                    <th>Descripcion</th>
                    <th>Departamento</th>
                     <th>Proveedor</th>
                     <th>Area</th>
                    <th>Imagen</th>
                 
                    <th>Eliminar</th>
                </tr>
                </thead>

                <tbody>
                    @foreach (ML.Producto producto in Model.Productos)
                    {
                    <tr>
                        <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Producto", new { IdProducto = producto.IdProducto})"> <i class="bi bi-pencil-square" style="color: ivory"></i></a></td>
                        
                        <td style="display :none;"> @producto.IdProducto</td>

                        <td>@producto.Nombre</td>
                        <td>@producto.PrecioUnitario</td>
                        <td>@producto.Stock</td>
                    

                        <td> @producto.Descripcion</td>


               

                        <td style="display :none;"> @producto.Departamento.IdDepartamento</td>

                        <td> @producto.Departamento.Nombre</td>    
                        
                        <td style="display :none;"> @producto.Proveedor.IdProveedor</td>

                        <td> @producto.Proveedor.Nombre</td> 
                        
                        <td style="display :none;"> @producto.Area.IdArea</td>

                        <td> @producto.Area.Nombre</td> 
                        
                          @if (producto.Imagen != null)
                            {
@*
                                <img id="Img" src="data:image/*;base64,@producto.Imagen" style="width:150px ; height:150px" />*@
                                 <td style ="text-align: center; vertical-align: middle;"><img src="data:image/*;base64,@producto.Imagen" style="width:50px ; height:50px" /></td>
                            }
                            else
                            {
                               @* <img id="Img" src="~/Imagen/SinProducto.jpg" style="width:150px ; height:150px" />*@
                                <td style ="text-align: center; vertical-align: middle;"><img src="~/Imagen/SinProducto.jpg" width="50px" height="50px" id="Img" /></td>
                            }
                        
 

                        <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Producto", new { IdProducto = producto.IdProducto })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"> <i class="bi bi-eraser-fill" style="color: mintcream"></i></a></td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>



@section Scripts
{

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

<script>
    $(document).ready(function () {
        $('#tblProducto').DataTable({
            searching: false,
            "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
            autoWidth: false,
            columnDefs: [
                {
                    targets: ['_all'],
                    className: 'mdc-data-table__cell',
                },
            ],
            language: {
                url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
            },
         });
    });



</script>

}

PL/Views/Producto/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Producto", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>$('#modalValidacion').modal();</script>

PL/Views/Producto/VentaProducto.cshtml
@model ML.Producto
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Productos</h2>

<div class="row">
    <div class="col-md-12">
        <h5>Administrador de Ventas </h5>
      
    </div>
</div>

    @* Encabezado *@
     <div class="container">
           <h3 class="text-black"> Filtrar por:  </h3>
          
           <div class="row">
 
              @using (Html.BeginForm("GetAll", "VentaProducto", FormMethod.Post,new { enctype = "multipart/form-data" }))
             {
                 <div class="col-md-3">
                   @Html.DropDownListFor(model => model.Departamento.IdDepartamento, new SelectList(Model.Departamento.Departamentos, "IdDepartamento", "Nombre"), "Selecciona una opción", new { @class = "form-control" })
                 </div>
                 <div class="col-md-3">
                  @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @placeholder = "Nombre" })
                 </div>
                 <div class="col-md-3">
                 <input type="submit" value="Buscar" class="btn btn-success" />
                 </div>
             }
          </div>
         @Html.ActionLink("Agregar +", "Form", "Producto", htmlAttributes: new { @class = "btn btn-success" })
     </div>
     

     <div class="row">
        @foreach (ML.Producto producto in Model.Productos)
          {
             <div class="col mt-3 pt-3">
                  <div class="card text-white bg-dark border-success  mb-3 border-4 " style="width: 18rem;">
                     <img src="~/Imagen/SinProducto.jpg" class="card-img-top" style=" height:50%; width:100%;">
                         <div class="card-body ">
                         <h5 class="card-title card-header text-center bg-secondary" id="pNombre">@producto.Nombre</h5>
                         <p class="card-text" id="pPrecioUnitario">Precio: @producto.PrecioUnitario</p>
                         <p class="card-text" id="pStock">Stock: @producto.Stock</p>
                     @*  <p class="card-text" id="pIdProveedor">Proveedor: @producto.Proveedor.IdProveedor</p>*@
                         <p class="card-text" id="pProveedor">Proveedor: @producto.Proveedor.Nombre</p>
                      @* <p class="card-text" id="pDepartamento>Departamento: @producto.Departamento.IdDepartamento</p>*@
                         <p class="card-text" id="pDepartamento">Departamento: @producto.Departamento.Nombre</p>
                      @* <p class="card-text" id="pIdArea">Area: @producto.Area.IdArea</p>*@
                         <p class="card-text" id="pArea">Area: @producto.Area.Nombre</p>
                         <p class="card-text" id="pDescripcion">Descripcion: @producto.Descripcion</p>
                         </div>
                  </div>
             </div>
           }
     </div>

@section Scripts
{

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

<script>
    $(document).ready(function () {
        $('#tblProducto').DataTable({
            searching: false,
            "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
            autoWidth: false,
            columnDefs: [
                {
                    targets: ['_all'],
                    className: 'mdc-data-table__cell',
                },
            ],
            language: {
                url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
            },
         });
    });



</script>

}